### ISSUE TITLE
[FEATURE] Date and channel name in filename.

### ISSUE THREAD

**Issue by Vergenter** [SoTrxII/Pandora-cooking-server#4]
Would you change default file naming convention from 
`<id>.<container_extension>` 
to 
`<UTC_timestamp>-<channel_name>-<id>.<container_extension>`.
Example:
`2022-03-17T18_31_19.004Z-main-261253504.zip`
Reasoning:
- Information when recording started can be precious for users that manage a lot of them.
- Adding a channel name simplifies identification of recordings and it enables you to describe content with channel name.
- I believe that adding this information in some other way like metadata will be a much more complicated solution.

As I checked:

- start date is saved there:
https://github.com/SoTrxII/Pandora/blob/4d0d60e94240945f56ce7793e4c03f6128119e91/src/commands/stop-recording.ts#L24 

- channel name is accessed but not saved there:
https://github.com/SoTrxII/Pandora/blob/4d0d60e94240945f56ce7793e4c03f6128119e91/src/commands/start-recording.ts#L34

**Comment by SoTrxII** [comment]
Hi there,
Thanks for your feedback! This would indeed be quite useful.  

The start date is already logged by Pandora in the info file, but the channel name is indeed not saved at the moment, so this would require work on both the cooking server and Pandora itself.

That being said, I'm actually in the middle of a refactoring of Pandora, I'll leave this issue open and I'll be sure to include your request in the next release.

**Comment by SoTrxII** [comment]
Hey, 
So the naming convention was changed as you requested in the cooking server >v2.0.0 ! 
The current naming scheme is  
```
<timestamp>-<channel_name>-<id>.<container_extension>.
```
if the info file exists, and fallback to the old 
```
<id>.<container_extension>
```
otherwise.

Pandora itself changed a lot, as I wanted a more scalable deployment, less dependent on volumes. 

That being said, you should be able to use the cooking server >= v2.1.0 with Pandora v1.0.0, at it support the old naming scheme
